CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` ENUM('OWNER', 'USER') NOT NULL DEFAULT 'USER',
  `avatar_url` VARCHAR(200) NOT NULL,
  `session_id` INT NOT NULL,
  `birth_date` DATE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `last_activity` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `sessions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `session_id` TEXT NOT NULL,
  `session_ip` VARCHAR(100) NOT NULL,
  `session_device` VARCHAR(255) NOT NULL
);